config/routes.rb
Todo::Application.routes.draw do
  root :to => "projects#index"
  
  # map.resources :tasks, :has_many => :comments  
  # map.resources :projects, :has_many => :comments  
  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :comments
    resources :ownerships
  end


  
  # Kasutajad ja sessioonid
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new"

  resources :users
  resources :sessions
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, :polymorphic => true
  belongs_to :user
  attr_accessible :commentable_type, :content, :user_id

  validates :content, :presence=>true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :check_admin_status, :only => [:destroy]

	def create
		@commentable = find_commentable
		@user = 1
		params[:comment][:user_id] = current_user
		@comment = @commentable.comments.build(params[:comment])
		if @comment.save
			flash[:notice] = "Successfully saved comment."
		else
			flash[:alert] = "A comment without content."
		end
		redirect_to :back
	end

	def destroy
		@project = Project.find(params[:project_id])
		unless params[:task_id]
			@comment = @project.comments.find(params[:id])
		else
			@task = @project.tasks.find(params[:task_id])
			@comment = @task.comments.find(params[:id])
		end
		if @comment.destroy
			flash[:notice] = "Successfully destroyed comment."
		else
			flash[:alert] = "Something went wrong."
		end
		redirect_to :back
	end

	def find_commentable
		p = Project.find(params[:project_id])
		if params[:task_id]
			t = p.tasks.find(params[:task_id])
		else
			p
		end
		t || p
	end

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	  # Kirjutan üle, sest projecti id task kontrollerit kasutades muutuja project_id all. Muidu lihtsalt id
	  def has_access?(user_id = nil)
	    User.find_by_id(user_id || current_user).ownerships.find_by_project_id(params[:project_id])
	  end
end

app/views/comments/_comment.html.erb
<p>
	<h4><small><%= current_user.email %></small>
	<% if is_admin?(@project.id) %>
		<!-- kustutamine kutsutakse välja Taski peal -->
		<% if defined?(@task) %>
		<%= link_to "", project_task_comment_path(@project, @task, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: "icon-remove" %>
		<% else %>
		 <%= link_to "", project_comment_path(@project, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: "icon-remove" %>
		<% end %>
	<% end %>
	</h4>
</p>
<p>
	<h4><small><%= comment.created_at.strftime('%d.%m.%Y %H:%M') %></small></h4>
</p>
<p>
	<%= comment.content %>
</p>

app/views/comments/_form.html.erb
<%= form_for [@commentable, @project ,  @project.comments.build] do |f| %>
<p>
  <%= f.text_area :content, :placeholder=>"Content", :class=>"span8"%>
</p>
<p><%= f.submit "Submit" %></p>
<% end %>

app/views/comments/_form_task.html.erb
<%= form_for [@commentable, @project, @task, @task.comments.build] do |f| %>
<p>
  <%= f.text_area :content, :placeholder=>"Content", :class=>"span8" %>
</p>
<p><%= f.submit "Submit" %></p>
<% end %>

app/views/comments/index.html.erb
<div id="comments">
<% for comment in @comments %>
  <div class="comment">
    <%=simple_format comment.content %>
  </div>
<% end %>
</div>

<h2>New Comment</h2>
<%= form_for [@commentable, Comment.new] do |f| %>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/comments/new.html.erb
<h2>New Comment</h2>

<% form_for [@commentable, Comment.new] do |f| %>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>