config/routes.rb
Todo::Application.routes.draw do
  root :to => "projects#index"
  
  # map.resources :tasks, :has_many => :comments  
  # map.resources :projects, :has_many => :comments  
  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :comments
    resources :ownerships
  end


  
  # Kasutajad ja sessioonid
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new"

  resources :users
  resources :sessions
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :closed, :content, :deadline, :name, :user_id, :project_id
  has_many :comments, :as => :commentable, :dependent => :destroy
  belongs_to :user
  belongs_to :project

  validates :content, :presence => true, :length => { :maximum => 200 }
  validates :deadline, :presence => true
  validates :name, :presence => true, :length => { :maximum => 50 }
  validates :user_id, :presence => true
  validates	:project_id, :presence => true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :check_access_rights
  before_filter :check_admin_status, :only => [:edit, :update, :destroy]
  # # GET /tasks
  # # GET /tasks.json
  def index
    @project = Project.find(params[:project_id])
    @tasks = @project.tasks

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # # GET /tasks/1
  # # GET /tasks/1.json
  def show
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # # GET /tasks/new
  # GET /tasks/new.json
  def new
    @project = Project.find(params[:project_id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /tasks/1/edit
  def edit
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find params[:id]
  end

  # POST /tasks
  # POST /tasks.json
  def create
    # Kontrollin enne, kas kasutajal on üldse ligipääsuõigused projektile
    if has_access?(params[:assignee])
      @project = Project.find_by_id(params[:project_id])
      parameters = Hash.new
      parameters[:name] = params[:name]
      parameters[:content] = params[:desc]
      parameters[:deadline] = params[:deadline]
      parameters[:closed] = params[:closed]
      parameters[:user_id] = params[:assignee]
      parameters[:project_id] = params[:project_id]
      @task = @project.tasks.build(parameters)
      if @task.save!
        redirect_to [@project, @task], :notice => "Task successfully created!"
      else
        redirect_to :back, :alert => "Something went wrong! Please check your input data"
      end
    else
      redirect_to :back, :alert => "The user doesn't have access to the project!"
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find params[:id]
    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to project_task_path(params[:project_id], :task_id => params[:id]), notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find params[:id]
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_path(params[:project_id]), notice: 'Task was successfully deleted.'}
      format.json { head :no_content }
    end
  end

  private

  # Kirjutan üle, sest projecti id task kontrollerit kasutades muutuja project_id all.
  def has_access?(user_id = nil)
    User.find_by_id(user_id || current_user).ownerships.find_by_project_id(params[:project_id])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_tag(project_tasks_path(@project), :method=>'post') do %>
  <div class="field">
    <%= text_field_tag :name, nil, :placeholder=>"Name", :class=>"span8" %>
    <%= text_area_tag :desc, nil, :placeholder=>"Short description", :class=>"span8" %>
  <div class="field">
  <%= select_tag :assignee, options_for_select(@project.ownerships.collect{ |u| [u.user.email, u.user.id] }), :class => "span8" %>
  </div>
  <div class="field">
    <%= datetime_select :deadline, :prompt => {:day => 'Choose day', :month => 'Choose month', :year => 'Choose year', :hour=>"Choose hour"}, :discard_minute => true, :class=>"span8"%>
  </div>
  <p>
      <%= check_box_tag :closed %>
  </p>
  <div class="actions">
    <%= submit_tag "Submit", class: "btn" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<% if task.closed %>
  <tr class="green">
<% elsif task.deadline > Date.today %>
  <tr class="red">
<% else  %>
  <tr class="blue">
<% end %>
    <td><%= link_to task.name, project_task_path(@project, task) %></td>
    <td><%= task.content %></td>
    <td><%= task.deadline.strftime('%d.%m.%Y %H:%M') %></td>
    <td><%= User.find_by_id(task.user_id).email %></td>
    <% if is_admin?(@project)%>
    <td><%= link_to "", edit_project_task_path(@project, task), class: "icon-edit"%></td>
    <td><%= link_to "", project_task_path(@project, task), method: :delete, data: { confirm: 'Are you sure?' }, class: "icon-remove" %></td>
   	<% end %>
  </tr>
<br />

app/views/tasks/edit.html.erb
<%= form_for [@project, @task] do |f| %>
  <div class="field">
    <%= f.text_field :name, :placeholder=>"Name", :class=>"span12" %>
  </div>
  <div class="field">
    <%= f.text_area :content, :placeholder=>"Description", :class=>"span12" %>
  </div>
  <div class="field">
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :closed %><br />
    <%= f.check_box :closed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', project_tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th>Deadline</th>
    <th>Closed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.content %></td>
    <td><%= task.deadline %></td>
    <td><%= task.closed %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', project_tasks_path %>

app/views/tasks/show.html.erb
<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Content:</b>
  <%= @task.content %>
</p>
<p>
  <b>Deadline:</b>
  <%= @task.deadline %>
</p>

<p>
  <b>Assignee:</b>
  <%= User.find_by_id(@task.user_id).email %>
</p>

<p>
  <b>Finished?</b>
  <% if @task.closed %>
    yes
  <% else %>
    no
  <% end %>
</p>

 <h4> Comments</h4>
  <%= render @task.comments %>

 <h4> Add a comment</h4>
  <%= render "comments/form_task" %>
<% if is_admin?(@project) %>
<%= link_to 'Edit', edit_project_task_path(@project, @task) %> |
<% end %>
<%= link_to 'Back', projects_path %>