config/routes.rb
Todo::Application.routes.draw do
  root :to => "projects#index"
  
  # map.resources :tasks, :has_many => :comments  
  # map.resources :projects, :has_many => :comments  
  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :comments
    resources :ownerships
  end


  
  # Kasutajad ja sessioonid
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new"

  resources :users
  resources :sessions
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  description :text
#

class Project < ActiveRecord::Base
  attr_accessible :name, :description
  has_many :tasks, :dependent => :destroy
  has_many :ownerships, :dependent => :destroy
  has_many :users, :through =>:ownerships
  has_many :comments, :as => :commentable, :dependent => :destroy

  validates :name, :presence => true, :length => { :maximum => 50 }
  validates :description, :length => { :maximum => 200 }, :presence => true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :check_access_rights, :only => [:show, :edit, :update, :destroy]
  before_filter :check_admin_status, :only => [:edit, :update, :destroy]
  def index
      @projects = current_user.projects
      respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = current_user.projects.find_by_id(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    respond_to do |format|
      if @project.save
        Ownership.create(:user_id => current_user.id, :project_id => @project.id, :owner => true)
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div class="alert alert-error">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name,  :placeholder => "Name" %>
  </div>
  <div class="field">
    <%= f.text_field :description,  :placeholder => "Short description"%>
  </div>
  <div class="actions">
    <%= f.submit "Create!" , class: "btn"%>
  </div>
<% end %>

app/views/projects/_stranger.html.erb
Sorry, you don't have access to the project!

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= render "ownership/form" %>

<!-- Kuvan kasutajaõigused -->
<table>
  <thead>
    <td class="bold">User</td>
    <td class="bold">Access rights</td>
    <td></td>
  </thead>
  <% @project.ownerships.each do |ownership| %>
    <tr>
      <td>  <%= ownership.user.email %></td>
      <% if ownership.owner? %>
      <td>  Read/Write </td>
      <% else %>
      <td> Read </td>
      <% end %>
      <td>
        <% unless ownership.user == current_user %>
        <%= link_to 'Delete', project_ownership_path(@project, ownership), :method => :delete, :confirm => "Are you sure?", class: "btn"%>
        <% end %>
      </td>
    </tr>
 <% end %>
 </table>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<table style="width: 200px">
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><h4><%= link_to project.name, project_path(project.id) %></h4></td>
    <td>
      <% if is_admin?(project.id) %>
      <%= link_to "", edit_project_path(project), class: "icon-edit"%>
      <% end %>
    </td>
    <td>
      <% if is_admin?(project.id) %>
      <%= link_to "", project, method: :delete, data: { confirm: 'Are you sure?' }, class: "icon-remove" %>
      <% end %>
    </td>
  </tr>
  <tr>
    <td colspan="3"><h4><small><%= project.description %></small></h4></td>
  </tr>
<% end %>
</table>
<br />
<h4><%= link_to 'Create a new Project', new_project_path %></h4>

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/show.html.erb
<p>
<h4><%= @project.name %></h4>
<h4><small><%= @project.description %></small></h4>
</p>
<h4>Tasks
	<% if is_admin? %>
	<%= link_to "", new_project_task_path(@project.id), :class=>"icon-plus",:alt=>"alt text" %>
	<% end %>
</h4>
<table id="myTable" class="span7">
<tr>
  <th>Name</th>
  <th>Content</th>
  <th>Deadline</th>
  <th>Assignee</th>
  <th></th>
  <th></th>
</tr>
<%= render @project.tasks %>
</table>
<br>
<h4> Comments</h4>
<%= render @project.comments %>

<h4> Add a comment</h4>
<%= render "comments/form" %>

<% if is_admin? %>
<%= link_to 'Edit', edit_project_path(@project) %> |
<% end %>
<%= link_to 'Back', projects_path %>