config/routes.rb
Todo::Application.routes.draw do
  root :to => "projects#index"
  
  # map.resources :tasks, :has_many => :comments  
  # map.resources :projects, :has_many => :comments  
  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :comments
    resources :ownerships
  end


  
  # Kasutajad ja sessioonid
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new"

  resources :users
  resources :sessions
end

app/views/layouts/_loggedin.html.erb
<body>
<header class="navbar navbar-fixed-top">  
  <div class="navbar-inner">  
    <div class="container">  
    <ul class="nav">  
	  <li class="active">  
	    <a class="brand" href="/">TODO</a>  
	  </li>  
	  <li><%= link_to "Home", '/' %></li>
	</ul>
	<ul class="nav">  
	  <li class="dropdown">  
	    <a href="#"  
	          class="dropdown-toggle"  
	          data-toggle="dropdown">  
	          Projects  
	          <b class="caret"></b>  
	    </a>  
	    <ul class="dropdown-menu">  
  	     <li><%= link_to "Create a new project", '/projects/new' %></li>  
		  <li><%= link_to "My projects", '/projects' %></li>  
	    </ul>  
	  </li>  
	</ul> 
	<ul class="nav">  
	  <li><a href="#">Account</a></li>
	  <li><%= link_to "Log out!",  log_out_path %></li>   
	</ul>
    </div>  
  </div>  
</header>  
<div class="container" id="wrapper">
	<%= yield %>
</div>
</body>

app/views/layouts/_loggedout.html.erb
Please log in!
<%= render "sessions/login" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
<body>
<% if current_user %>
<header class="navbar navbar-fixed-top">  
  <div class="navbar-inner">  
    <div class="container">  
    <ul class="nav">  
    <li class="active">  
      <a class="brand" href="/">TODO</a>  
    </li>  
    <li><%= link_to "Home", '/' %></li>
  </ul>
  <ul class="nav">  
    <li class="dropdown">  
      <a href="#"  
            class="dropdown-toggle"  
            data-toggle="dropdown">  
            Projects  
            <b class="caret"></b>  
      </a>  
      <ul class="dropdown-menu">  
         <li><%= link_to "Create a new project", '/projects/new' %></li>  
      <li><%= link_to "My projects", '/projects' %></li>  
      </ul>  
    </li>  
  </ul> 
  <ul class="nav">  
    <li><%= link_to "Account",  edit_user_path(current_user) %></li>
    <li><%= link_to "Log out!",  log_out_path %></li>   
  </ul>
    </div>  
  </div>  
</header>
<% end %> 
<div class="container" id="wrapper">
  <% if flash[:alert] %>
<div class="alert alert-error" ><%= flash[:alert] %></div>
<% end %>
<% if flash[:notice] %>
<div class="alert alert-success" ><%= flash[:notice] %></div>
<% end %>
  <%= yield %>
</div>
</body>
</html>